---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-21T11:42:17Z"
  name: carts-canary
  resourceVersion: "933293"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: f846394a-0c53-11ea-accf-42010a840fc2
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
